### ISSUE TITLE
TypeError: MapwizeClient.syncVenueBeacons is not a function

### ISSUE THREAD

**Issue by zijam** [IndoorLocation/meraki-indoor-location#11]
merakiAccessPointsToMapwize.js script is calling _syncVenueBeacons_ function from mapwize-node-api package, which doesn't exists.

```
meraki-indoor-location/meraki-configurator/merakiAccessPointsToMapwize.js:144
        MapwizeClient.syncVenueBeacons(program.mapwizeVenueId, mapwizeFormatOfMerakiAccessPoint, {filter : filter, delete : true}, next);
                      ^

TypeError: MapwizeClient.syncVenueBeacons is not a function
    at /meraki-indoor-location/meraki-configurator/merakiAccessPointsToMapwize.js:144:23
    at /meraki-indoor-location/node_modules/async/dist/async.js:3866:24
    at replenish (/meraki-indoor-location/node_modules/async/dist/async.js:998:17)
    at iterateeCallback (/meraki-indoor-location/node_modules/async/dist/async.js:983:17)
    at /meraki-indoor-location/node_modules/async/dist/async.js:958:16
    at /meraki-indoor-location/node_modules/async/dist/async.js:3871:13
    at /meraki-indoor-location/node_modules/async/dist/async.js:473:16
    at replenish (/meraki-indoor-location/node_modules/async/dist/async.js:993:25)
    at iterateeCallback (/meraki-indoor-location/node_modules/async/dist/async.js:983:17)
    at /meraki-indoor-location/node_modules/async/dist/async.js:958:16
```

I'm running on master branch c8774ca062008654aa2efe76b9a8b05711b0255a

**Comment by mathieugerard** [comment]
Hi Zijam. Indeed, thanks for reporting both issues. It seems that this part of the configurator is missing some updates. I'm working on a quick fix.

**Comment by mathieugerard** [comment]
The issue has been fixed. Let us know if you have any other question regarding Meraki and Mapwize.
